name: Generate Changelog

on:
  push:
    tags:
      - "v*" # Trigger when pushing tags like v1.0.0

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for changelog

      # 2. Setup Ruby (github-changelog-generator is Ruby gem)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      # 3. Install github-changelog-generator
      - name: Install github-changelog-generator
        run: gem install github_changelog_generator

      # 4. Generate changelog
      - name: Generate CHANGELOG.md
        run: |
          github_changelog_generator \
            --user dovutuan \
            --project lalog \
            --token ${{ secrets.TOKEN }} \
            --exclude-labels "duplicate,question,invalid,wontfix" \
            --no-verbose

      # 5. Commit & Push changelog
      - name: Commit CHANGELOG.md
        run: |
          git config user.name "dovutuan"
          git config user.email "tuando.0598@gmail.com"
          git add CHANGELOG.md
          git commit -m "docs: update changelog for $GITHUB_REF_NAME" || echo "No changes to commit"
          git push origin HEAD:master
